name: ci

on: [push, pull_request]

jobs:
  dockerlint:
    runs-on: ubuntu-latest
    name: Docker lint
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: lint
      uses: luke142367/Docker-Lint-Action@v1.0.0
      with:
        target: Dockerfile
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  flake8-lint:
    runs-on: ubuntu-latest
    name: Python lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: flake8 Lint
        uses: py-actions/flake8@v1

  markdownlint:
    runs-on: ubuntu-latest
    name: Markdown lint
    steps:
    - uses: actions/checkout@v2
    - uses: DavidAnson/markdownlint-cli2-action@v4
      with:
        globs: |
          **/*.md

  gitleaks:
    runs-on: ubuntu-latest
    name: Gitleaks
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: gitleaks-action
      uses: zricethezav/gitleaks-action@master